const categories = [
    'Action',
    'Adult',
    'Anime',
    'Comedy',
    'Comic',
    'Chuyển sinh',
    'Cooking',
    'Cổ đại',
    'Doujinshi',
    'Drama',
    'Ecchi',
    'Fantasy',
    'Gender Bender',
    'Harem',
    'Historical',
    'Horror',
    'Josei',
    'Live Action',
    'Martial Arts',
    'Manga',
    'Manhua',
    'Manhwa',
    'Mature',
    'Mecha',
    'Mystery',
    'One shot',
    'Psychological',
    'Romance',
    'School Life',
    'Sci-fi',
    'Seinen',
    'Shoujo',
    'Shoujo Ai',
    'Shounen',
    'Shounen Ai',
    'Slice of Life',
    'Smut',
    'Soft yuri',
    'Sport',
    'Supernatural',
    'Tragedy',
    'Webtoon',
    'Trinh Thám',
    'Truyện scan',
    'Truyện Màu',
    'Thiếu Nhi',
    'Xuyên Không',
];

const status = ['Tất cả', 'Đang tiến hành', 'Đã hoàn thành'];

export { categories, status };
